fastlane_require 'dotenv'

before_all do
  Dotenv.load('.env')
end

lane :build_and_sign do
  update_code_signing_settings(
    code_sign_identity: 'Developer ID Application',
    use_automatic_signing: false,
    path: 'teleport.xcodeproj'
  )
  get_certificates(
    generate_apple_certs: false,
    platform: 'macos',
    type: 'developer_id_application'
  )
  get_provisioning_profile(
    app_identifier: 'com.abyssoft.teleport',
    platform: 'macos',
    developer_id: true
  )
  build_mac_app(
    export_method: 'developer-id',
    output_directory: 'build',
    scheme: 'teleport',
    skip_package_pkg: true
  )
  notarize(
    package: './build/teleport.app'
  )
end

lane :draft_release do
  build_and_sign
end
